// @generated
// This file is @generated by prost-build.
/// One block's worth of AgentRail activity on Solana, in the shape of the shared schema
/// (indexer/schema.graphql). `ens_node` is the join key shared with the ENS and EVM sources.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Activity {
    #[prost(message, repeated, tag="1")]
    pub mandates: ::prost::alloc::vec::Vec<Mandate>,
    #[prost(message, repeated, tag="2")]
    pub permissions: ::prost::alloc::vec::Vec<Permission>,
    #[prost(message, repeated, tag="3")]
    pub actions: ::prost::alloc::vec::Vec<Action>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Mandate {
    /// "<ens_node hex>:solana"
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// 0x-prefixed 32 bytes
    #[prost(string, tag="2")]
    pub ens_node: ::prost::alloc::string::String,
    /// "solana"
    #[prost(string, tag="3")]
    pub chain: ::prost::alloc::string::String,
    /// base58
    #[prost(string, tag="4")]
    pub owner: ::prost::alloc::string::String,
    /// base58
    #[prost(string, tag="5")]
    pub agent: ::prost::alloc::string::String,
    #[prost(int64, tag="6")]
    pub expiry: i64,
    #[prost(bool, tag="7")]
    pub active: bool,
    /// base58 signature of the create / revoke
    #[prost(string, tag="8")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="9")]
    pub slot: u64,
    #[prost(int64, tag="10")]
    pub timestamp: i64,
    /// base58 mandate account
    #[prost(string, tag="11")]
    pub pda: ::prost::alloc::string::String,
    /// "create_mandate" | "revoke_mandate"
    #[prost(string, tag="12")]
    pub kind: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Permission {
    /// "<mandate id>:<program_id>"
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub mandate_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub ens_node: ::prost::alloc::string::String,
    /// base58: destination token account (payments) or program id (verify)
    #[prost(string, tag="4")]
    pub target: ::prost::alloc::string::String,
    /// hex discriminators, left-aligned in 8 bytes
    #[prost(string, repeated, tag="5")]
    pub instructions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint32, tag="6")]
    pub discriminator_size: u32,
    #[prost(uint64, tag="7")]
    pub per_tx_limit: u64,
    #[prost(uint64, tag="8")]
    pub total_limit: u64,
    #[prost(string, tag="9")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub slot: u64,
    #[prost(int64, tag="11")]
    pub timestamp: i64,
    /// "add_permission" | "remove_permission"
    #[prost(string, tag="12")]
    pub kind: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Action {
    /// "<signature>:<instruction index>"
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// "<ens_node hex>:solana"
    #[prost(string, tag="2")]
    pub mandate_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub ens_node: ::prost::alloc::string::String,
    /// "solana"
    #[prost(string, tag="4")]
    pub chain: ::prost::alloc::string::String,
    #[prost(int64, tag="5")]
    pub timestamp: i64,
    /// base58: destination token account (execute_payment) or sibling program id (verify)
    #[prost(string, tag="6")]
    pub target: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub amount: u64,
    /// false when the transaction failed: THE row this index exists for
    #[prost(bool, tag="8")]
    pub allowed: bool,
    /// OVER_BUDGET | NOT_PERMITTED | EXPIRED | REVOKED | FAILED; empty when allowed
    #[prost(string, tag="9")]
    pub block_reason: ::prost::alloc::string::String,
    /// base58 signature
    #[prost(string, tag="10")]
    pub tx_hash: ::prost::alloc::string::String,
    /// "execute_payment" | "verify"
    #[prost(string, tag="11")]
    pub kind: ::prost::alloc::string::String,
    /// raw Anchor error number (6007 …); 0 when allowed
    #[prost(uint32, tag="12")]
    pub error_code: u32,
    /// base58 signer
    #[prost(string, tag="13")]
    pub agent: ::prost::alloc::string::String,
    #[prost(uint64, tag="14")]
    pub slot: u64,
    /// base58 mandate account
    #[prost(string, tag="15")]
    pub pda: ::prost::alloc::string::String,
    /// "PerTxLimitExceeded" …; empty when allowed
    #[prost(string, tag="16")]
    pub error_name: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
