// Generated by `substreams protogen`, trimmed to what this crate uses: our output types and the
// entity-change sink types. The Solana block model comes from the substreams-solana crate.
pub mod agentrail {
    pub mod v1 {
        include!("agentrail.v1.rs");
    }
}
pub mod sf {
    pub mod substreams {
        pub mod sink {
            pub mod entity {
                pub mod v1 {
                    include!("sf.substreams.sink.entity.v1.rs");
                }
            }
        }
    }
}
