// @generated
// This file is @generated by prost-build.
/// One block's SPL Token activity on the watched account. One message per instruction.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenActivity {
    #[prost(message, repeated, tag="1")]
    pub transfers: ::prost::alloc::vec::Vec<Transfer>,
    #[prost(message, repeated, tag="2")]
    pub transfer_checkeds: ::prost::alloc::vec::Vec<TransferChecked>,
    #[prost(message, repeated, tag="3")]
    pub approves: ::prost::alloc::vec::Vec<Approve>,
    #[prost(message, repeated, tag="4")]
    pub revokes: ::prost::alloc::vec::Vec<Revoke>,
}
/// SPL Token `Transfer` (discriminator 3): accounts \[source, destination, authority\]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transfer {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub source: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub destination: ::prost::alloc::string::String,
    #[prost(uint64, tag="5")]
    pub amount: u64,
    #[prost(string, tag="6")]
    pub authority: ::prost::alloc::string::String,
    /// authority == the mandate PDA (the delegate signed through the program)
    #[prost(bool, tag="7")]
    pub via_mandate: bool,
    /// reached through CPI (the way execute_payment moves tokens)
    #[prost(bool, tag="8")]
    pub inner: bool,
}
/// SPL Token `TransferChecked` (discriminator 12): accounts \[source, mint, destination, authority\]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransferChecked {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub source: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub mint: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub destination: ::prost::alloc::string::String,
    #[prost(uint64, tag="6")]
    pub amount: u64,
    #[prost(uint32, tag="7")]
    pub decimals: u32,
    #[prost(string, tag="8")]
    pub authority: ::prost::alloc::string::String,
    #[prost(bool, tag="9")]
    pub via_mandate: bool,
    #[prost(bool, tag="10")]
    pub inner: bool,
}
/// SPL Token `Approve` (discriminator 4): accounts \[source, delegate, owner\]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Approve {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub source: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub delegate: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub owner: ::prost::alloc::string::String,
    #[prost(uint64, tag="6")]
    pub amount: u64,
    #[prost(bool, tag="7")]
    pub delegate_is_mandate: bool,
}
/// SPL Token `Revoke` (discriminator 5): accounts \[source, owner\]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Revoke {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub source: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub owner: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
