// Generated by `substreams protogen`, trimmed to this crate's output type.
pub mod agentrail {
    pub mod token {
        pub mod v1 {
            include!("agentrail.token.v1.rs");
        }
    }
}
